apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-monitoring-kube-prometheus-alertmanager
  namespace: monitoring
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: blackhole
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 1h
      routes:
        - receiver: telegram-notifications
          matchers:
            - alertname=~"DevSecOps.*|KubePodCrashLooping|KubePodNotReady|KubeDeploymentReplicasMismatch"

    receivers:
      - name: blackhole
      - name: telegram-notifications
        telegram_configs:
          - bot_token: "REPLACE_WITH_TELEGRAM_BOT_TOKEN"
            chat_id: 1708149171
            parse_mode: "HTML"
            message: |
              🚨 <b>Kubernetes Alert Notification</b>

              {{ range .Alerts }}
              <b>Alert:</b> {{ .Labels.alertname }}
              <b>Status:</b> {{ .Status }}
              <b>Severity:</b> {{ .Labels.severity }}
              <b>Namespace:</b> {{ .Labels.namespace }}
              <b>Pod:</b> {{ .Labels.pod }}

              <b>Summary:</b>
              {{ .Annotations.summary }}

              <b>Description:</b>
              {{ .Annotations.description }}

              -------------------------
              {{ end }}
